on:
  push:
    branches: [main]
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'
name: client
env:
  NODE_VERSION: 18
jobs: 
  lint:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./client
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Code Lint
        run: npm run lint
