name: Lint Client 

on:
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 18

jobs: 
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./client
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Code Lint
        run: npm run lint
