on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'server/**'
  schedule:
    - cron:  '7 7 * * *'
name: server / rolling
jobs:
  # https://twitter.com/alcuadrado/status/1571291687837732873
  update:
    runs-on: ubuntu-latest
    name: beta / updated
    defaults:
      run:
        working-directory: ./server
    # There's no point running this if no Cargo.lock was checked in in the
    # first place, since we'd just redo what happened in the regular test job.
    # Unfortunately, hashFiles only works in if on steps, so we reepeat it.
    # if: hashFiles('Cargo.lock') != ''
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install beta
        if: hashFiles('server/Cargo.lock') != ''
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          default: true
      - name: cargo update
        if: hashFiles('server/Cargo.lock') != ''
        uses: actions-rs/cargo@v1
        with:
          command: update
      - name: cargo test
        if: hashFiles('server/Cargo.lock') != ''
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --all-features --all-targets --manifest-path server/Cargo.toml
        env:
          RUSTFLAGS: -D deprecated
